version: '3.8'

services:
  db:
    image: mysql:8.0
    ports:
      - '6603:3306'
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: web
    volumes:
      - mysql_data:/var/lib/mysql

  php:
    build: .
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    links:
      - db

volumes:
  mysql_data: